[general]
static=yes
writeprotect=no
clearglobalvars=no

[default]
exten => _X.,1,NoOp(Incoming WebRTC Call to Stasis App)
 same => n,Answer()
 same => n,Stasis(dongdo-call-app)
 same => n,Hangup()

[dongdo-stasis]
exten => s,1,NoOp(Stasis Call Entry)
 same => n,Answer()
 same => n,Stasis(dongdo-call-app)
 same => n,Hangup()

exten => _[a-zA-Z0-9_-].,1,NoOp(Named Stasis Entry ${EXTEN})
 same => n,Answer()
 same => n,Stasis(dongdo-call-app)
 same => n,Hangup()
