// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cases.sql

package chatdb

import (
	"context"
	"time"

	"github.com/hoainguyen222/DongDo_CS_V2/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignCase = `-- name: AssignCase :exec
UPDATE chat_cases
SET status = 'HUMAN_CS_ACTIVE'::case_status, assigned_cs = $1, updated_at = NOW()
WHERE session_id = $2
`

type AssignCaseParams struct {
	AssignedCs pgtype.Text `json:"assigned_cs"`
	SessionID  string      `json:"session_id"`
}

func (q *Queries) AssignCase(ctx context.Context, arg AssignCaseParams) error {
	_, err := q.db.Exec(ctx, assignCase, arg.AssignedCs, arg.SessionID)
	return err
}

const deleteAllCases = `-- name: DeleteAllCases :exec
DELETE FROM chat_cases
`

func (q *Queries) DeleteAllCases(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllCases)
	return err
}

const deleteCase = `-- name: DeleteCase :exec
DELETE FROM chat_cases WHERE session_id = $1
`

func (q *Queries) DeleteCase(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, deleteCase, sessionID)
	return err
}

const getCase = `-- name: GetCase :one
SELECT id, session_id, guest_id, customer_name, customer_phone,
       status, assigned_cs, last_message, resolution_note, created_at, updated_at
FROM chat_cases
WHERE session_id = $1
`

type GetCaseRow struct {
	ID             int64             `json:"id"`
	SessionID      string            `json:"session_id"`
	GuestID        pgtype.UUID       `json:"guest_id"`
	CustomerName   string            `json:"customer_name"`
	CustomerPhone  string            `json:"customer_phone"`
	Status         domain.CaseStatus `json:"status"`
	AssignedCs     pgtype.Text       `json:"assigned_cs"`
	LastMessage    pgtype.Text       `json:"last_message"`
	ResolutionNote pgtype.Text       `json:"resolution_note"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
}

func (q *Queries) GetCase(ctx context.Context, sessionID string) (GetCaseRow, error) {
	row := q.db.QueryRow(ctx, getCase, sessionID)
	var i GetCaseRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.GuestID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Status,
		&i.AssignedCs,
		&i.LastMessage,
		&i.ResolutionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCaseDetailWithGuest = `-- name: GetCaseDetailWithGuest :one
SELECT
    c.id, c.session_id, c.guest_id, c.customer_name, c.customer_phone,
    c.status, c.assigned_cs, c.last_message, c.resolution_note, c.created_at, c.updated_at,
    g.display_name AS guest_display_name,
    g.phone        AS guest_phone
FROM chat_cases c
LEFT JOIN guests g ON c.guest_id = g.guest_id
WHERE c.session_id = $1
`

type GetCaseDetailWithGuestRow struct {
	ID               int64             `json:"id"`
	SessionID        string            `json:"session_id"`
	GuestID          pgtype.UUID       `json:"guest_id"`
	CustomerName     string            `json:"customer_name"`
	CustomerPhone    string            `json:"customer_phone"`
	Status           domain.CaseStatus `json:"status"`
	AssignedCs       pgtype.Text       `json:"assigned_cs"`
	LastMessage      pgtype.Text       `json:"last_message"`
	ResolutionNote   pgtype.Text       `json:"resolution_note"`
	CreatedAt        time.Time         `json:"created_at"`
	UpdatedAt        time.Time         `json:"updated_at"`
	GuestDisplayName pgtype.Text       `json:"guest_display_name"`
	GuestPhone       pgtype.Text       `json:"guest_phone"`
}

func (q *Queries) GetCaseDetailWithGuest(ctx context.Context, sessionID string) (GetCaseDetailWithGuestRow, error) {
	row := q.db.QueryRow(ctx, getCaseDetailWithGuest, sessionID)
	var i GetCaseDetailWithGuestRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.GuestID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Status,
		&i.AssignedCs,
		&i.LastMessage,
		&i.ResolutionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestDisplayName,
		&i.GuestPhone,
	)
	return i, err
}

const getRecentCompletedChats = `-- name: GetRecentCompletedChats :many
SELECT id, session_id, guest_id, customer_name, customer_phone,
       status, assigned_cs, last_message, resolution_note, created_at, updated_at
FROM chat_cases
WHERE status IN ('RESOLVED'::case_status, 'AI_ACTIVE'::case_status)
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type GetRecentCompletedChatsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetRecentCompletedChatsRow struct {
	ID             int64             `json:"id"`
	SessionID      string            `json:"session_id"`
	GuestID        pgtype.UUID       `json:"guest_id"`
	CustomerName   string            `json:"customer_name"`
	CustomerPhone  string            `json:"customer_phone"`
	Status         domain.CaseStatus `json:"status"`
	AssignedCs     pgtype.Text       `json:"assigned_cs"`
	LastMessage    pgtype.Text       `json:"last_message"`
	ResolutionNote pgtype.Text       `json:"resolution_note"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
}

func (q *Queries) GetRecentCompletedChats(ctx context.Context, arg GetRecentCompletedChatsParams) ([]GetRecentCompletedChatsRow, error) {
	rows, err := q.db.Query(ctx, getRecentCompletedChats, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentCompletedChatsRow{}
	for rows.Next() {
		var i GetRecentCompletedChatsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.GuestID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.Status,
			&i.AssignedCs,
			&i.LastMessage,
			&i.ResolutionNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCases = `-- name: ListCases :many
SELECT id, session_id, guest_id, customer_name, customer_phone,
       status, assigned_cs, last_message, resolution_note, created_at, updated_at
FROM chat_cases
ORDER BY updated_at DESC
`

type ListCasesRow struct {
	ID             int64             `json:"id"`
	SessionID      string            `json:"session_id"`
	GuestID        pgtype.UUID       `json:"guest_id"`
	CustomerName   string            `json:"customer_name"`
	CustomerPhone  string            `json:"customer_phone"`
	Status         domain.CaseStatus `json:"status"`
	AssignedCs     pgtype.Text       `json:"assigned_cs"`
	LastMessage    pgtype.Text       `json:"last_message"`
	ResolutionNote pgtype.Text       `json:"resolution_note"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
}

func (q *Queries) ListCases(ctx context.Context) ([]ListCasesRow, error) {
	rows, err := q.db.Query(ctx, listCases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCasesRow{}
	for rows.Next() {
		var i ListCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.GuestID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.Status,
			&i.AssignedCs,
			&i.LastMessage,
			&i.ResolutionNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCasesByStatus = `-- name: ListCasesByStatus :many
SELECT id, session_id, guest_id, customer_name, customer_phone,
       status, assigned_cs, last_message, resolution_note, created_at, updated_at
FROM chat_cases
WHERE status = $1::case_status
ORDER BY updated_at DESC
`

type ListCasesByStatusRow struct {
	ID             int64             `json:"id"`
	SessionID      string            `json:"session_id"`
	GuestID        pgtype.UUID       `json:"guest_id"`
	CustomerName   string            `json:"customer_name"`
	CustomerPhone  string            `json:"customer_phone"`
	Status         domain.CaseStatus `json:"status"`
	AssignedCs     pgtype.Text       `json:"assigned_cs"`
	LastMessage    pgtype.Text       `json:"last_message"`
	ResolutionNote pgtype.Text       `json:"resolution_note"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
}

func (q *Queries) ListCasesByStatus(ctx context.Context, dollar_1 domain.CaseStatus) ([]ListCasesByStatusRow, error) {
	rows, err := q.db.Query(ctx, listCasesByStatus, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCasesByStatusRow{}
	for rows.Next() {
		var i ListCasesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.GuestID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.Status,
			&i.AssignedCs,
			&i.LastMessage,
			&i.ResolutionNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveCase = `-- name: ResolveCase :exec
UPDATE chat_cases
SET status = 'RESOLVED'::case_status,
    assigned_cs = $1,
    resolution_note = $2,
    updated_at = NOW()
WHERE session_id = $3
`

type ResolveCaseParams struct {
	AssignedCs     pgtype.Text `json:"assigned_cs"`
	ResolutionNote pgtype.Text `json:"resolution_note"`
	SessionID      string      `json:"session_id"`
}

func (q *Queries) ResolveCase(ctx context.Context, arg ResolveCaseParams) error {
	_, err := q.db.Exec(ctx, resolveCase, arg.AssignedCs, arg.ResolutionNote, arg.SessionID)
	return err
}

const upsertCase = `-- name: UpsertCase :one

INSERT INTO chat_cases (
    session_id, guest_id, customer_name, customer_phone,
    status, assigned_cs, last_message, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
ON CONFLICT (session_id) DO UPDATE SET
    customer_name = CASE
        WHEN EXCLUDED.customer_name <> '' AND EXCLUDED.customer_name <> 'Khách hàng'
            THEN EXCLUDED.customer_name
        ELSE chat_cases.customer_name
    END,
    customer_phone = CASE
        WHEN EXCLUDED.customer_phone <> ''
            THEN EXCLUDED.customer_phone
        ELSE chat_cases.customer_phone
    END,
    status = CASE
        WHEN chat_cases.status = 'HUMAN_CS_ACTIVE' AND EXCLUDED.status = 'NEEDS_HUMAN_CS'::case_status
            THEN chat_cases.status
        ELSE EXCLUDED.status
    END,
    last_message = COALESCE(NULLIF(EXCLUDED.last_message, ''), chat_cases.last_message),
    assigned_cs  = COALESCE(NULLIF(EXCLUDED.assigned_cs, ''), chat_cases.assigned_cs),
    updated_at = NOW()
RETURNING id, session_id, guest_id, customer_name, customer_phone,
          status, assigned_cs, last_message, resolution_note, created_at, updated_at
`

type UpsertCaseParams struct {
	SessionID     string            `json:"session_id"`
	GuestID       pgtype.UUID       `json:"guest_id"`
	CustomerName  string            `json:"customer_name"`
	CustomerPhone string            `json:"customer_phone"`
	Status        domain.CaseStatus `json:"status"`
	AssignedCs    pgtype.Text       `json:"assigned_cs"`
	LastMessage   pgtype.Text       `json:"last_message"`
}

type UpsertCaseRow struct {
	ID             int64             `json:"id"`
	SessionID      string            `json:"session_id"`
	GuestID        pgtype.UUID       `json:"guest_id"`
	CustomerName   string            `json:"customer_name"`
	CustomerPhone  string            `json:"customer_phone"`
	Status         domain.CaseStatus `json:"status"`
	AssignedCs     pgtype.Text       `json:"assigned_cs"`
	LastMessage    pgtype.Text       `json:"last_message"`
	ResolutionNote pgtype.Text       `json:"resolution_note"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
}

// ============================================================
// Chat cases (CS inbox)
// ============================================================
func (q *Queries) UpsertCase(ctx context.Context, arg UpsertCaseParams) (UpsertCaseRow, error) {
	row := q.db.QueryRow(ctx, upsertCase,
		arg.SessionID,
		arg.GuestID,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.Status,
		arg.AssignedCs,
		arg.LastMessage,
	)
	var i UpsertCaseRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.GuestID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Status,
		&i.AssignedCs,
		&i.LastMessage,
		&i.ResolutionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
