// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: guests.sql

package chatdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countGuests = `-- name: CountGuests :one
SELECT COUNT(*)
FROM guests g
LEFT JOIN LATERAL (
    SELECT session_id, last_message, status, updated_at
    FROM chat_cases
    WHERE guest_id = g.guest_id
       OR (g.display_name <> '' AND customer_name = g.display_name)
    ORDER BY updated_at DESC
    LIMIT 1
) c ON true
WHERE (
    $1::text IS NULL
    OR LOWER(g.display_name) LIKE '%' || LOWER($1::text) || '%'
    OR LOWER(g.phone) LIKE '%' || LOWER($1::text) || '%'
    OR LOWER(g.guest_id::text) LIKE '%' || LOWER($1::text) || '%'
    OR LOWER(c.last_message) LIKE '%' || LOWER($1::text) || '%'
)
`

func (q *Queries) CountGuests(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countGuests, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuest = `-- name: CreateGuest :one

INSERT INTO guests (guest_id, display_name, phone, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, guest_id, display_name, phone, created_at
`

type CreateGuestParams struct {
	GuestID     uuid.UUID   `json:"guest_id"`
	DisplayName string      `json:"display_name"`
	Phone       pgtype.Text `json:"phone"`
}

// ============================================================
// Guests (customer pre-chat)
// ============================================================
func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error) {
	row := q.db.QueryRow(ctx, createGuest, arg.GuestID, arg.DisplayName, arg.Phone)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.GuestID,
		&i.DisplayName,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGuest = `-- name: DeleteGuest :exec
DELETE FROM guests WHERE guest_id = $1
`

func (q *Queries) DeleteGuest(ctx context.Context, guestID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGuest, guestID)
	return err
}

const getGuestByID = `-- name: GetGuestByID :one
SELECT id, guest_id, display_name, phone, created_at
FROM guests
WHERE guest_id = $1
`

func (q *Queries) GetGuestByID(ctx context.Context, guestID uuid.UUID) (Guest, error) {
	row := q.db.QueryRow(ctx, getGuestByID, guestID)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.GuestID,
		&i.DisplayName,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const listGuestsWithLastCase = `-- name: ListGuestsWithLastCase :many
SELECT
    g.id,
    g.guest_id::text                              AS guest_id,
    g.display_name,
    COALESCE(g.phone, '')                         AS phone,
    COALESCE(c.session_id, '')                    AS last_session_id,
    COALESCE(c.last_message, '')                  AS last_message,
    COALESCE(c.status::text, '')                  AS last_status,
    g.created_at,
    COALESCE(c.updated_at, g.created_at)          AS updated_at
FROM guests g
LEFT JOIN LATERAL (
    SELECT session_id, last_message, status, updated_at
    FROM chat_cases
    WHERE guest_id = g.guest_id
       OR (g.display_name <> '' AND customer_name = g.display_name)
    ORDER BY updated_at DESC
    LIMIT 1
) c ON true
WHERE (
    $1::text IS NULL
    OR LOWER(g.display_name) LIKE '%' || LOWER($1::text) || '%'
    OR LOWER(g.phone) LIKE '%' || LOWER($1::text) || '%'
    OR LOWER(g.guest_id::text) LIKE '%' || LOWER($1::text) || '%'
    OR LOWER(c.last_message) LIKE '%' || LOWER($1::text) || '%'
)
ORDER BY g.created_at DESC
LIMIT $2 OFFSET $3
`

type ListGuestsWithLastCaseParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListGuestsWithLastCaseRow struct {
	ID            int64       `json:"id"`
	GuestID       string      `json:"guest_id"`
	DisplayName   string      `json:"display_name"`
	Phone         string      `json:"phone"`
	LastSessionID string      `json:"last_session_id"`
	LastMessage   string      `json:"last_message"`
	LastStatus    interface{} `json:"last_status"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

func (q *Queries) ListGuestsWithLastCase(ctx context.Context, arg ListGuestsWithLastCaseParams) ([]ListGuestsWithLastCaseRow, error) {
	rows, err := q.db.Query(ctx, listGuestsWithLastCase, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuestsWithLastCaseRow{}
	for rows.Next() {
		var i ListGuestsWithLastCaseRow
		if err := rows.Scan(
			&i.ID,
			&i.GuestID,
			&i.DisplayName,
			&i.Phone,
			&i.LastSessionID,
			&i.LastMessage,
			&i.LastStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncActiveCasesForGuest = `-- name: SyncActiveCasesForGuest :exec
UPDATE chat_cases
SET customer_name = $2, customer_phone = $3, updated_at = NOW()
WHERE guest_id = $1
`

type SyncActiveCasesForGuestParams struct {
	GuestID       pgtype.UUID `json:"guest_id"`
	CustomerName  string      `json:"customer_name"`
	CustomerPhone string      `json:"customer_phone"`
}

func (q *Queries) SyncActiveCasesForGuest(ctx context.Context, arg SyncActiveCasesForGuestParams) error {
	_, err := q.db.Exec(ctx, syncActiveCasesForGuest, arg.GuestID, arg.CustomerName, arg.CustomerPhone)
	return err
}

const updateGuest = `-- name: UpdateGuest :exec
UPDATE guests
SET display_name = $2, phone = $3
WHERE guest_id = $1
`

type UpdateGuestParams struct {
	GuestID     uuid.UUID   `json:"guest_id"`
	DisplayName string      `json:"display_name"`
	Phone       pgtype.Text `json:"phone"`
}

func (q *Queries) UpdateGuest(ctx context.Context, arg UpdateGuestParams) error {
	_, err := q.db.Exec(ctx, updateGuest, arg.GuestID, arg.DisplayName, arg.Phone)
	return err
}
