// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package chatdb

import (
	"context"
	"time"

	"github.com/hoainguyen222/DongDo_CS_V2/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllMessages = `-- name: DeleteAllMessages :exec
DELETE FROM chat_messages
`

func (q *Queries) DeleteAllMessages(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllMessages)
	return err
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :exec
DELETE FROM chat_messages WHERE session_id = $1
`

func (q *Queries) DeleteSessionMessages(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, deleteSessionMessages, sessionID)
	return err
}

const getSessionHistory = `-- name: GetSessionHistory :many
SELECT id, session_id, sender_type, sender_id, content, client_msg_id, is_learned, created_at
FROM chat_messages
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetSessionHistory(ctx context.Context, sessionID string) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getSessionHistory, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SenderType,
			&i.SenderID,
			&i.Content,
			&i.ClientMsgID,
			&i.IsLearned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnlearnedMessages = `-- name: GetUnlearnedMessages :many
SELECT id, session_id, sender_type, sender_id, content, created_at
FROM chat_messages
WHERE is_learned = FALSE
ORDER BY session_id, created_at
`

type GetUnlearnedMessagesRow struct {
	ID         int64             `json:"id"`
	SessionID  string            `json:"session_id"`
	SenderType domain.SenderType `json:"sender_type"`
	SenderID   pgtype.Text       `json:"sender_id"`
	Content    string            `json:"content"`
	CreatedAt  time.Time         `json:"created_at"`
}

func (q *Queries) GetUnlearnedMessages(ctx context.Context) ([]GetUnlearnedMessagesRow, error) {
	rows, err := q.db.Query(ctx, getUnlearnedMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnlearnedMessagesRow{}
	for rows.Next() {
		var i GetUnlearnedMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SenderType,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :one

INSERT INTO chat_messages (session_id, sender_type, sender_id, content, client_msg_id, is_learned, created_at)
VALUES ($1, $2, $3, $4, $5, FALSE, NOW())
ON CONFLICT (client_msg_id) WHERE client_msg_id IS NOT NULL DO UPDATE SET content = EXCLUDED.content
RETURNING id, session_id, sender_type, sender_id, content, client_msg_id, is_learned, created_at
`

type InsertMessageParams struct {
	SessionID   string            `json:"session_id"`
	SenderType  domain.SenderType `json:"sender_type"`
	SenderID    pgtype.Text       `json:"sender_id"`
	Content     string            `json:"content"`
	ClientMsgID pgtype.UUID       `json:"client_msg_id"`
}

// ============================================================
// Chat messages
// ============================================================
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.SessionID,
		arg.SenderType,
		arg.SenderID,
		arg.Content,
		arg.ClientMsgID,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SenderType,
		&i.SenderID,
		&i.Content,
		&i.ClientMsgID,
		&i.IsLearned,
		&i.CreatedAt,
	)
	return i, err
}

const markMessagesLearned = `-- name: MarkMessagesLearned :exec
UPDATE chat_messages SET is_learned = TRUE WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkMessagesLearned(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, markMessagesLearned, dollar_1)
	return err
}

const resetLearnedFlags = `-- name: ResetLearnedFlags :exec
UPDATE chat_messages SET is_learned = FALSE
`

func (q *Queries) ResetLearnedFlags(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetLearnedFlags)
	return err
}
