// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package chatdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/hoainguyen222/DongDo_CS_V2/internal/domain"
)

type Querier interface {
	AssignCase(ctx context.Context, arg AssignCaseParams) error
	CountCases(ctx context.Context, dollar_1 string) (int64, error)
	CountCasesSearch(ctx context.Context, arg CountCasesSearchParams) (int64, error)
	// ============================================================
	// Guests (customer pre-chat)
	// ============================================================
	CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error)
	DeleteAllCases(ctx context.Context) error
	DeleteAllMessages(ctx context.Context) error
	DeleteCase(ctx context.Context, sessionID string) error
	DeleteGuest(ctx context.Context, guestID uuid.UUID) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetCase(ctx context.Context, sessionID string) (GetCaseRow, error)
	GetCaseDetailWithGuest(ctx context.Context, sessionID string) (GetCaseDetailWithGuestRow, error)
	GetGuestByID(ctx context.Context, guestID uuid.UUID) (Guest, error)
	GetRecentCompletedChats(ctx context.Context, arg GetRecentCompletedChatsParams) ([]GetRecentCompletedChatsRow, error)
	GetSessionHistory(ctx context.Context, sessionID string) ([]ChatMessage, error)
	GetUnlearnedMessages(ctx context.Context) ([]GetUnlearnedMessagesRow, error)
	// ============================================================
	// Chat messages
	// ============================================================
	InsertMessage(ctx context.Context, arg InsertMessageParams) (ChatMessage, error)
	ListCases(ctx context.Context) ([]ListCasesRow, error)
	ListCasesByStatus(ctx context.Context, dollar_1 domain.CaseStatus) ([]ListCasesByStatusRow, error)
	// Paginated variant used by HandleListCases so we never load the full table
	// into Go memory before slicing. The shape is identical to ListCases; only
	// LIMIT/OFFSET differs. statusFilter empty string means "any status".
	ListCasesPage(ctx context.Context, arg ListCasesPageParams) ([]ListCasesPageRow, error)
	ListGuestsWithLastCase(ctx context.Context) ([]ListGuestsWithLastCaseRow, error)
	MarkMessagesLearned(ctx context.Context, dollar_1 []int64) error
	ResetLearnedFlags(ctx context.Context) error
	ResolveCase(ctx context.Context, arg ResolveCaseParams) error
	// Search-and-paginate variant for HandleListCases. The OR-of-LIKE pattern
	// is acceptable for the small admin-inbox dataset; if it ever grows past
	// ~50k rows swap to a trigram index (pg_trgm).
	SearchCasesPage(ctx context.Context, arg SearchCasesPageParams) ([]SearchCasesPageRow, error)
	SyncActiveCasesForGuest(ctx context.Context, arg SyncActiveCasesForGuestParams) error
	UpdateGuest(ctx context.Context, arg UpdateGuestParams) error
	// ============================================================
	// Chat cases (CS inbox)
	// ============================================================
	UpsertCase(ctx context.Context, arg UpsertCaseParams) (UpsertCaseRow, error)
}

var _ Querier = (*Queries)(nil)
