// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package chatdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/hoainguyen222/DongDo_CS_V2/internal/domain"
)

type Querier interface {
	AssignCase(ctx context.Context, arg AssignCaseParams) error
	// ============================================================
	// Guests (customer pre-chat)
	// ============================================================
	CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error)
	DeleteAllCases(ctx context.Context) error
	DeleteAllMessages(ctx context.Context) error
	DeleteCase(ctx context.Context, sessionID string) error
	DeleteGuest(ctx context.Context, guestID uuid.UUID) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetCase(ctx context.Context, sessionID string) (GetCaseRow, error)
	GetCaseDetailWithGuest(ctx context.Context, sessionID string) (GetCaseDetailWithGuestRow, error)
	GetGuestByID(ctx context.Context, guestID uuid.UUID) (Guest, error)
	GetRecentCompletedChats(ctx context.Context, arg GetRecentCompletedChatsParams) ([]GetRecentCompletedChatsRow, error)
	GetSessionHistory(ctx context.Context, sessionID string) ([]ChatMessage, error)
	GetUnlearnedMessages(ctx context.Context) ([]GetUnlearnedMessagesRow, error)
	// ============================================================
	// Chat messages
	// ============================================================
	InsertMessage(ctx context.Context, arg InsertMessageParams) (ChatMessage, error)
	ListCases(ctx context.Context) ([]ListCasesRow, error)
	ListCasesByStatus(ctx context.Context, dollar_1 domain.CaseStatus) ([]ListCasesByStatusRow, error)
	ListGuestsWithLastCase(ctx context.Context) ([]ListGuestsWithLastCaseRow, error)
	MarkMessagesLearned(ctx context.Context, dollar_1 []int64) error
	ResetLearnedFlags(ctx context.Context) error
	ResolveCase(ctx context.Context, arg ResolveCaseParams) error
	SyncActiveCasesForGuest(ctx context.Context, arg SyncActiveCasesForGuestParams) error
	UpdateGuest(ctx context.Context, arg UpdateGuestParams) error
	// ============================================================
	// Chat cases (CS inbox)
	// ============================================================
	UpsertCase(ctx context.Context, arg UpsertCaseParams) (UpsertCaseRow, error)
}

var _ Querier = (*Queries)(nil)
