// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: partner_dashboard.sql

package partnerdb

import (
	"context"
	"time"
)

const getDashboardAutomationTrendDaily = `-- name: GetDashboardAutomationTrendDaily :many
SELECT
    DATE_TRUNC('day', created_at)::timestamptz AS date_day,
    COUNT(*)::int AS total_cases,
    COUNT(CASE WHEN status = 'AI_ACTIVE' OR status = 'RESOLVED' THEN 1 END)::int AS ai_cases,
    COUNT(CASE WHEN status = 'NEEDS_HUMAN_CS' OR status = 'HUMAN_CS_ACTIVE' THEN 1 END)::int AS handoff_cases
FROM chat_cases
WHERE created_at >= $1 AND created_at <= $2
GROUP BY DATE_TRUNC('day', created_at)
ORDER BY date_day ASC
`

type GetDashboardAutomationTrendDailyParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetDashboardAutomationTrendDailyRow struct {
	DateDay      time.Time `json:"date_day"`
	TotalCases   int32     `json:"total_cases"`
	AiCases      int32     `json:"ai_cases"`
	HandoffCases int32     `json:"handoff_cases"`
}

func (q *Queries) GetDashboardAutomationTrendDaily(ctx context.Context, arg GetDashboardAutomationTrendDailyParams) ([]GetDashboardAutomationTrendDailyRow, error) {
	rows, err := q.db.Query(ctx, getDashboardAutomationTrendDaily, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDashboardAutomationTrendDailyRow{}
	for rows.Next() {
		var i GetDashboardAutomationTrendDailyRow
		if err := rows.Scan(
			&i.DateDay,
			&i.TotalCases,
			&i.AiCases,
			&i.HandoffCases,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardKpiSummary = `-- name: GetDashboardKpiSummary :one

SELECT
    (SELECT COUNT(*) FROM chat_cases cc WHERE cc.created_at >= $1 AND cc.created_at <= $2)::int AS total_conversations,
    (SELECT COUNT(*) FROM chat_cases cc
        WHERE (cc.status = 'AI_ACTIVE' OR cc.status = 'RESOLVED') AND cc.created_at >= $1 AND cc.created_at <= $2)::int AS ai_resolved_count,
    (SELECT COUNT(*) FROM chat_cases cc
        WHERE cc.status = 'NEEDS_HUMAN_CS' AND cc.created_at >= $1 AND cc.created_at <= $2)::int AS human_handoff_count,
    COALESCE((SELECT AVG(cf.rating)::float FROM csat_feedback cf
        WHERE cf.created_at >= $1 AND cf.created_at <= $2), 4.9)::float AS avg_csat
`

type GetDashboardKpiSummaryParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetDashboardKpiSummaryRow struct {
	TotalConversations int32   `json:"total_conversations"`
	AiResolvedCount    int32   `json:"ai_resolved_count"`
	HumanHandoffCount  int32   `json:"human_handoff_count"`
	AvgCsat            float64 `json:"avg_csat"`
}

// ============================================================
// Partner — dashboard KPIs & trend
// ============================================================
func (q *Queries) GetDashboardKpiSummary(ctx context.Context, arg GetDashboardKpiSummaryParams) (GetDashboardKpiSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDashboardKpiSummary, arg.CreatedAt, arg.CreatedAt_2)
	var i GetDashboardKpiSummaryRow
	err := row.Scan(
		&i.TotalConversations,
		&i.AiResolvedCount,
		&i.HumanHandoffCount,
		&i.AvgCsat,
	)
	return i, err
}
