// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: partner_reports.sql

package partnerdb

import (
	"context"
	"time"

	"github.com/hoainguyen222/DongDo_CS_V2/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAILearningReportStats = `-- name: GetAILearningReportStats :one

SELECT
    (SELECT COUNT(*) FROM learning_queue WHERE status = 'PENDING')::int  AS pending_count,
    (SELECT COUNT(*) FROM learning_queue WHERE status = 'APPROVED')::int  AS approved_count,
    (SELECT COUNT(*) FROM learning_queue WHERE status = 'REJECTED')::int  AS rejected_count,
    (SELECT COUNT(*) FROM learning_queue)::int                           AS total_learning_items
`

type GetAILearningReportStatsRow struct {
	PendingCount       int32 `json:"pending_count"`
	ApprovedCount      int32 `json:"approved_count"`
	RejectedCount      int32 `json:"rejected_count"`
	TotalLearningItems int32 `json:"total_learning_items"`
}

// ============================================================
// 7. AI Learning Report
// ============================================================
func (q *Queries) GetAILearningReportStats(ctx context.Context) (GetAILearningReportStatsRow, error) {
	row := q.db.QueryRow(ctx, getAILearningReportStats)
	var i GetAILearningReportStatsRow
	err := row.Scan(
		&i.PendingCount,
		&i.ApprovedCount,
		&i.RejectedCount,
		&i.TotalLearningItems,
	)
	return i, err
}

const getAIPerformanceMetrics = `-- name: GetAIPerformanceMetrics :one

SELECT
    COUNT(*)::int AS total_cases,
    COUNT(CASE WHEN cc.status = 'AI_ACTIVE' OR cc.status = 'RESOLVED' THEN 1 END)::int AS ai_resolved_cases,
    COUNT(CASE WHEN cc.status = 'NEEDS_HUMAN_CS' OR cc.status = 'HUMAN_CS_ACTIVE' THEN 1 END)::int AS handoff_cases,
    COALESCE((SELECT AVG(cf.rating)::float FROM csat_feedback cf
        WHERE cf.target_type = 'ai' AND cf.created_at >= $1 AND cf.created_at <= $2), 4.91)::float AS avg_ai_csat
FROM chat_cases cc
WHERE cc.created_at >= $1 AND cc.created_at <= $2
`

type GetAIPerformanceMetricsParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetAIPerformanceMetricsRow struct {
	TotalCases      int32   `json:"total_cases"`
	AiResolvedCases int32   `json:"ai_resolved_cases"`
	HandoffCases    int32   `json:"handoff_cases"`
	AvgAiCsat       float64 `json:"avg_ai_csat"`
}

// ============================================================
// 2. AI Performance Report
// ============================================================
func (q *Queries) GetAIPerformanceMetrics(ctx context.Context, arg GetAIPerformanceMetricsParams) (GetAIPerformanceMetricsRow, error) {
	row := q.db.QueryRow(ctx, getAIPerformanceMetrics, arg.CreatedAt, arg.CreatedAt_2)
	var i GetAIPerformanceMetricsRow
	err := row.Scan(
		&i.TotalCases,
		&i.AiResolvedCases,
		&i.HandoffCases,
		&i.AvgAiCsat,
	)
	return i, err
}

const getAITrendDaily = `-- name: GetAITrendDaily :many
SELECT
    DATE_TRUNC('day', created_at)::timestamptz AS date_day,
    COUNT(*)::int AS total_cases,
    COUNT(CASE WHEN status = 'AI_ACTIVE' OR status = 'RESOLVED' THEN 1 END)::int AS ai_resolved_cases
FROM chat_cases
WHERE created_at >= $1 AND created_at <= $2
GROUP BY DATE_TRUNC('day', created_at)
ORDER BY date_day ASC
`

type GetAITrendDailyParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetAITrendDailyRow struct {
	DateDay         time.Time `json:"date_day"`
	TotalCases      int32     `json:"total_cases"`
	AiResolvedCases int32     `json:"ai_resolved_cases"`
}

func (q *Queries) GetAITrendDaily(ctx context.Context, arg GetAITrendDailyParams) ([]GetAITrendDailyRow, error) {
	rows, err := q.db.Query(ctx, getAITrendDaily, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAITrendDailyRow{}
	for rows.Next() {
		var i GetAITrendDailyRow
		if err := rows.Scan(&i.DateDay, &i.TotalCases, &i.AiResolvedCases); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCXMetricsReport = `-- name: GetCXMetricsReport :one

SELECT
    COUNT(*)::int                                            AS total_feedback_count,
    COALESCE(AVG(rating)::float, 4.89)::float                AS avg_csat_score,
    COUNT(CASE WHEN cf.rating >= 4 THEN 1 END)::int         AS positive_feedback_count,
    COUNT(CASE WHEN cf.rating <= 2 THEN 1 END)::int         AS negative_feedback_count
FROM csat_feedback cf
WHERE cf.created_at >= $1 AND cf.created_at <= $2
`

type GetCXMetricsReportParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetCXMetricsReportRow struct {
	TotalFeedbackCount    int32   `json:"total_feedback_count"`
	AvgCsatScore          float64 `json:"avg_csat_score"`
	PositiveFeedbackCount int32   `json:"positive_feedback_count"`
	NegativeFeedbackCount int32   `json:"negative_feedback_count"`
}

// ============================================================
// 4. Customer Experience (CX) Report
// ============================================================
func (q *Queries) GetCXMetricsReport(ctx context.Context, arg GetCXMetricsReportParams) (GetCXMetricsReportRow, error) {
	row := q.db.QueryRow(ctx, getCXMetricsReport, arg.CreatedAt, arg.CreatedAt_2)
	var i GetCXMetricsReportRow
	err := row.Scan(
		&i.TotalFeedbackCount,
		&i.AvgCsatScore,
		&i.PositiveFeedbackCount,
		&i.NegativeFeedbackCount,
	)
	return i, err
}

const getGeneralOverviewMetrics = `-- name: GetGeneralOverviewMetrics :one

SELECT
    (SELECT COUNT(*) FROM guests g WHERE g.created_at >= $1 AND g.created_at <= $2)::int        AS total_customers,
    (SELECT COUNT(*) FROM chat_cases cc WHERE cc.created_at >= $1 AND cc.created_at <= $2)::int  AS total_cases,
    (SELECT COUNT(*) FROM chat_cases cc WHERE cc.status = 'RESOLVED' AND cc.created_at >= $1 AND cc.created_at <= $2)::int
                                                                                            AS resolved_cases,
    (SELECT COUNT(*) FROM chat_cases cc WHERE (cc.status = 'AI_ACTIVE' OR cc.status = 'NEEDS_HUMAN_CS' OR cc.status = 'HUMAN_CS_ACTIVE')
        AND cc.created_at >= $1 AND cc.created_at <= $2)::int                             AS open_cases
`

type GetGeneralOverviewMetricsParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetGeneralOverviewMetricsRow struct {
	TotalCustomers int32 `json:"total_customers"`
	TotalCases     int32 `json:"total_cases"`
	ResolvedCases  int32 `json:"resolved_cases"`
	OpenCases      int32 `json:"open_cases"`
}

// ============================================================
// 1. General Overview Report
// ============================================================
func (q *Queries) GetGeneralOverviewMetrics(ctx context.Context, arg GetGeneralOverviewMetricsParams) (GetGeneralOverviewMetricsRow, error) {
	row := q.db.QueryRow(ctx, getGeneralOverviewMetrics, arg.CreatedAt, arg.CreatedAt_2)
	var i GetGeneralOverviewMetricsRow
	err := row.Scan(
		&i.TotalCustomers,
		&i.TotalCases,
		&i.ResolvedCases,
		&i.OpenCases,
	)
	return i, err
}

const getHourlyOperationalLoad = `-- name: GetHourlyOperationalLoad :many

SELECT
    EXTRACT(HOUR FROM created_at)::int AS hour_of_day,
    COUNT(*)::int AS total_messages
FROM chat_messages
WHERE created_at >= $1 AND created_at <= $2
GROUP BY EXTRACT(HOUR FROM created_at)
ORDER BY hour_of_day ASC
`

type GetHourlyOperationalLoadParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetHourlyOperationalLoadRow struct {
	HourOfDay     int32 `json:"hour_of_day"`
	TotalMessages int32 `json:"total_messages"`
}

// ============================================================
// 5. Operational Load Report
// ============================================================
func (q *Queries) GetHourlyOperationalLoad(ctx context.Context, arg GetHourlyOperationalLoadParams) ([]GetHourlyOperationalLoadRow, error) {
	rows, err := q.db.Query(ctx, getHourlyOperationalLoad, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHourlyOperationalLoadRow{}
	for rows.Next() {
		var i GetHourlyOperationalLoadRow
		if err := rows.Scan(&i.HourOfDay, &i.TotalMessages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIssueAnalysisReport = `-- name: GetIssueAnalysisReport :many

SELECT
    category_name,
    COUNT(*)::int AS total_requests,
    COUNT(CASE WHEN ai_resolved = TRUE THEN 1 END)::int AS ai_resolved_count
FROM issue_categories
WHERE created_at >= $1 AND created_at <= $2
GROUP BY category_name
ORDER BY total_requests DESC
`

type GetIssueAnalysisReportParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetIssueAnalysisReportRow struct {
	CategoryName    string `json:"category_name"`
	TotalRequests   int32  `json:"total_requests"`
	AiResolvedCount int32  `json:"ai_resolved_count"`
}

// ============================================================
// 6. Issue Analysis Report
// ============================================================
func (q *Queries) GetIssueAnalysisReport(ctx context.Context, arg GetIssueAnalysisReportParams) ([]GetIssueAnalysisReportRow, error) {
	rows, err := q.db.Query(ctx, getIssueAnalysisReport, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetIssueAnalysisReportRow{}
	for rows.Next() {
		var i GetIssueAnalysisReportRow
		if err := rows.Scan(&i.CategoryName, &i.TotalRequests, &i.AiResolvedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaffPerformanceReport = `-- name: GetStaffPerformanceReport :many

SELECT
    COALESCE(c.assigned_cs, 'Chưa phân công')  AS staff_username,
    u.full_name                                AS staff_full_name,
    u.role::text                               AS staff_role,
    COUNT(c.id)::int                           AS total_cases_handled,
    COUNT(CASE WHEN c.status = 'RESOLVED' THEN 1 END)::int AS resolved_cases,
    COALESCE((SELECT AVG(cf.rating)::float FROM csat_feedback cf
        WHERE cf.staff_username = c.assigned_cs AND cf.created_at >= $1 AND cf.created_at <= $2), 4.95)::float
                                               AS avg_csat
FROM chat_cases c
LEFT JOIN users u ON c.assigned_cs = u.username
WHERE c.created_at >= $1 AND c.created_at <= $2
  AND c.assigned_cs <> ''
GROUP BY c.assigned_cs, u.full_name, u.role
ORDER BY total_cases_handled DESC
`

type GetStaffPerformanceReportParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetStaffPerformanceReportRow struct {
	StaffUsername     string      `json:"staff_username"`
	StaffFullName     pgtype.Text `json:"staff_full_name"`
	StaffRole         string      `json:"staff_role"`
	TotalCasesHandled int32       `json:"total_cases_handled"`
	ResolvedCases     int32       `json:"resolved_cases"`
	AvgCsat           float64     `json:"avg_csat"`
}

// ============================================================
// 3. Staff Performance Report
// ============================================================
func (q *Queries) GetStaffPerformanceReport(ctx context.Context, arg GetStaffPerformanceReportParams) ([]GetStaffPerformanceReportRow, error) {
	rows, err := q.db.Query(ctx, getStaffPerformanceReport, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStaffPerformanceReportRow{}
	for rows.Next() {
		var i GetStaffPerformanceReportRow
		if err := rows.Scan(
			&i.StaffUsername,
			&i.StaffFullName,
			&i.StaffRole,
			&i.TotalCasesHandled,
			&i.ResolvedCases,
			&i.AvgCsat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCSATFeedback = `-- name: InsertCSATFeedback :one
INSERT INTO csat_feedback (session_id, rating, feedback_text, target_type, staff_username, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, session_id, rating, feedback_text, target_type, staff_username, created_at
`

type InsertCSATFeedbackParams struct {
	SessionID     string      `json:"session_id"`
	Rating        int32       `json:"rating"`
	FeedbackText  pgtype.Text `json:"feedback_text"`
	TargetType    string      `json:"target_type"`
	StaffUsername pgtype.Text `json:"staff_username"`
}

func (q *Queries) InsertCSATFeedback(ctx context.Context, arg InsertCSATFeedbackParams) (CsatFeedback, error) {
	row := q.db.QueryRow(ctx, insertCSATFeedback,
		arg.SessionID,
		arg.Rating,
		arg.FeedbackText,
		arg.TargetType,
		arg.StaffUsername,
	)
	var i CsatFeedback
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Rating,
		&i.FeedbackText,
		&i.TargetType,
		&i.StaffUsername,
		&i.CreatedAt,
	)
	return i, err
}

const insertIssueCategory = `-- name: InsertIssueCategory :one
INSERT INTO issue_categories (session_id, category_name, ai_resolved, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, session_id, category_name, ai_resolved, created_at
`

type InsertIssueCategoryParams struct {
	SessionID    string `json:"session_id"`
	CategoryName string `json:"category_name"`
	AiResolved   bool   `json:"ai_resolved"`
}

func (q *Queries) InsertIssueCategory(ctx context.Context, arg InsertIssueCategoryParams) (IssueCategory, error) {
	row := q.db.QueryRow(ctx, insertIssueCategory, arg.SessionID, arg.CategoryName, arg.AiResolved)
	var i IssueCategory
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CategoryName,
		&i.AiResolved,
		&i.CreatedAt,
	)
	return i, err
}

const listInteractedCustomers = `-- name: ListInteractedCustomers :many
SELECT id, guest_id, display_name, phone, created_at
FROM guests
WHERE created_at >= $1 AND created_at <= $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListInteractedCustomersParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListInteractedCustomers(ctx context.Context, arg ListInteractedCustomersParams) ([]Guest, error) {
	rows, err := q.db.Query(ctx, listInteractedCustomers,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Guest{}
	for rows.Next() {
		var i Guest
		if err := rows.Scan(
			&i.ID,
			&i.GuestID,
			&i.DisplayName,
			&i.Phone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverviewCases = `-- name: ListOverviewCases :many
SELECT id, session_id, guest_id, customer_name, customer_phone,
       status, assigned_cs, last_message, resolution_note, created_at, updated_at
FROM chat_cases
WHERE created_at >= $1 AND created_at <= $2
  AND ($3::text = 'ALL' OR assigned_cs = $3)
ORDER BY updated_at DESC
LIMIT $4 OFFSET $5
`

type ListOverviewCasesParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Column3     string    `json:"column_3"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

type ListOverviewCasesRow struct {
	ID             int64             `json:"id"`
	SessionID      string            `json:"session_id"`
	GuestID        pgtype.UUID       `json:"guest_id"`
	CustomerName   string            `json:"customer_name"`
	CustomerPhone  string            `json:"customer_phone"`
	Status         domain.CaseStatus `json:"status"`
	AssignedCs     pgtype.Text       `json:"assigned_cs"`
	LastMessage    pgtype.Text       `json:"last_message"`
	ResolutionNote pgtype.Text       `json:"resolution_note"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
}

func (q *Queries) ListOverviewCases(ctx context.Context, arg ListOverviewCasesParams) ([]ListOverviewCasesRow, error) {
	rows, err := q.db.Query(ctx, listOverviewCases,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverviewCasesRow{}
	for rows.Next() {
		var i ListOverviewCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.GuestID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.Status,
			&i.AssignedCs,
			&i.LastMessage,
			&i.ResolutionNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
