// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: partner_config.sql

package partnerdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuickTemplate = `-- name: CreateQuickTemplate :one
INSERT INTO quick_templates (title, category, content, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, title, category, content, created_by, created_at, updated_at
`

type CreateQuickTemplateParams struct {
	Title     string      `json:"title"`
	Category  string      `json:"category"`
	Content   string      `json:"content"`
	CreatedBy pgtype.Text `json:"created_by"`
}

func (q *Queries) CreateQuickTemplate(ctx context.Context, arg CreateQuickTemplateParams) (QuickTemplate, error) {
	row := q.db.QueryRow(ctx, createQuickTemplate,
		arg.Title,
		arg.Category,
		arg.Content,
		arg.CreatedBy,
	)
	var i QuickTemplate
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuickTemplate = `-- name: DeleteQuickTemplate :exec
DELETE FROM quick_templates WHERE id = $1
`

func (q *Queries) DeleteQuickTemplate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteQuickTemplate, id)
	return err
}

const getLatestSystemPrompt = `-- name: GetLatestSystemPrompt :one

SELECT id, system_prompt, llm_model, temperature, created_by, created_at
FROM system_prompt_history
ORDER BY created_at DESC
LIMIT 1
`

// ============================================================
// Partner — system prompt history
// ============================================================
func (q *Queries) GetLatestSystemPrompt(ctx context.Context) (SystemPromptHistory, error) {
	row := q.db.QueryRow(ctx, getLatestSystemPrompt)
	var i SystemPromptHistory
	err := row.Scan(
		&i.ID,
		&i.SystemPrompt,
		&i.LlmModel,
		&i.Temperature,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one

INSERT INTO system_audit_logs (action_type, details, performed_by, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, action_type, details, performed_by, created_at
`

type InsertAuditLogParams struct {
	ActionType  string      `json:"action_type"`
	Details     pgtype.Text `json:"details"`
	PerformedBy pgtype.Text `json:"performed_by"`
}

// ============================================================
// Partner — audit logs
// ============================================================
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (SystemAuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog, arg.ActionType, arg.Details, arg.PerformedBy)
	var i SystemAuditLog
	err := row.Scan(
		&i.ID,
		&i.ActionType,
		&i.Details,
		&i.PerformedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertSystemPromptHistory = `-- name: InsertSystemPromptHistory :one
INSERT INTO system_prompt_history (system_prompt, llm_model, temperature, created_by, created_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, system_prompt, llm_model, temperature, created_by, created_at
`

type InsertSystemPromptHistoryParams struct {
	SystemPrompt string         `json:"system_prompt"`
	LlmModel     string         `json:"llm_model"`
	Temperature  pgtype.Numeric `json:"temperature"`
	CreatedBy    pgtype.Text    `json:"created_by"`
}

func (q *Queries) InsertSystemPromptHistory(ctx context.Context, arg InsertSystemPromptHistoryParams) (SystemPromptHistory, error) {
	row := q.db.QueryRow(ctx, insertSystemPromptHistory,
		arg.SystemPrompt,
		arg.LlmModel,
		arg.Temperature,
		arg.CreatedBy,
	)
	var i SystemPromptHistory
	err := row.Scan(
		&i.ID,
		&i.SystemPrompt,
		&i.LlmModel,
		&i.Temperature,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, action_type, details, performed_by, created_at
FROM system_audit_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]SystemAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemAuditLog{}
	for rows.Next() {
		var i SystemAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActionType,
			&i.Details,
			&i.PerformedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuickTemplates = `-- name: ListQuickTemplates :many

SELECT id, title, category, content, created_by, created_at, updated_at
FROM quick_templates
ORDER BY id DESC
`

// ============================================================
// Partner — quick templates
// ============================================================
func (q *Queries) ListQuickTemplates(ctx context.Context) ([]QuickTemplate, error) {
	rows, err := q.db.Query(ctx, listQuickTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuickTemplate{}
	for rows.Next() {
		var i QuickTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Content,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many

SELECT id, role_name, feature_key, permission_level, can_view, can_edit, updated_at
FROM role_permissions
ORDER BY role_name, feature_key
`

// ============================================================
// Partner — role permissions (RBAC)
// ============================================================
func (q *Queries) ListRolePermissions(ctx context.Context) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, listRolePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolePermission{}
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(
			&i.ID,
			&i.RoleName,
			&i.FeatureKey,
			&i.PermissionLevel,
			&i.CanView,
			&i.CanEdit,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemErrors = `-- name: ListSystemErrors :many
SELECT id, source, title, details, severity, is_handled, suggested_fix, created_at
FROM system_errors
ORDER BY created_at DESC
`

func (q *Queries) ListSystemErrors(ctx context.Context) ([]SystemError, error) {
	rows, err := q.db.Query(ctx, listSystemErrors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemError{}
	for rows.Next() {
		var i SystemError
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Title,
			&i.Details,
			&i.Severity,
			&i.IsHandled,
			&i.SuggestedFix,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemPromptHistory = `-- name: ListSystemPromptHistory :many
SELECT id, system_prompt, llm_model, temperature, created_by, created_at
FROM system_prompt_history
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSystemPromptHistoryParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSystemPromptHistory(ctx context.Context, arg ListSystemPromptHistoryParams) ([]SystemPromptHistory, error) {
	rows, err := q.db.Query(ctx, listSystemPromptHistory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemPromptHistory{}
	for rows.Next() {
		var i SystemPromptHistory
		if err := rows.Scan(
			&i.ID,
			&i.SystemPrompt,
			&i.LlmModel,
			&i.Temperature,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSystemErrorHandled = `-- name: MarkSystemErrorHandled :exec
UPDATE system_errors SET is_handled = TRUE WHERE id = $1
`

func (q *Queries) MarkSystemErrorHandled(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markSystemErrorHandled, id)
	return err
}

const purgeOldSystemErrors = `-- name: PurgeOldSystemErrors :exec

DELETE FROM system_errors WHERE created_at < NOW() - INTERVAL '30 days'
`

// ============================================================
// Partner — system errors (auto-purge after 30 days)
// ============================================================
func (q *Queries) PurgeOldSystemErrors(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeOldSystemErrors)
	return err
}

const updateQuickTemplate = `-- name: UpdateQuickTemplate :exec
UPDATE quick_templates
SET title = $1, category = $2, content = $3, updated_at = NOW()
WHERE id = $4
`

type UpdateQuickTemplateParams struct {
	Title    string `json:"title"`
	Category string `json:"category"`
	Content  string `json:"content"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateQuickTemplate(ctx context.Context, arg UpdateQuickTemplateParams) error {
	_, err := q.db.Exec(ctx, updateQuickTemplate,
		arg.Title,
		arg.Category,
		arg.Content,
		arg.ID,
	)
	return err
}

const upsertRolePermission = `-- name: UpsertRolePermission :exec
INSERT INTO role_permissions (role_name, feature_key, permission_level, can_view, can_edit, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (role_name, feature_key) DO UPDATE
SET permission_level = EXCLUDED.permission_level,
    can_view         = EXCLUDED.can_view,
    can_edit         = EXCLUDED.can_edit,
    updated_at       = NOW()
`

type UpsertRolePermissionParams struct {
	RoleName        string `json:"role_name"`
	FeatureKey      string `json:"feature_key"`
	PermissionLevel string `json:"permission_level"`
	CanView         bool   `json:"can_view"`
	CanEdit         bool   `json:"can_edit"`
}

func (q *Queries) UpsertRolePermission(ctx context.Context, arg UpsertRolePermissionParams) error {
	_, err := q.db.Exec(ctx, upsertRolePermission,
		arg.RoleName,
		arg.FeatureKey,
		arg.PermissionLevel,
		arg.CanView,
		arg.CanEdit,
	)
	return err
}

const upsertSystemError = `-- name: UpsertSystemError :exec
INSERT INTO system_errors (id, source, title, details, severity, is_handled, suggested_fix, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET is_handled = EXCLUDED.is_handled
`

type UpsertSystemErrorParams struct {
	ID           string      `json:"id"`
	Source       string      `json:"source"`
	Title        string      `json:"title"`
	Details      pgtype.Text `json:"details"`
	Severity     string      `json:"severity"`
	IsHandled    bool        `json:"is_handled"`
	SuggestedFix pgtype.Text `json:"suggested_fix"`
	CreatedAt    time.Time   `json:"created_at"`
}

func (q *Queries) UpsertSystemError(ctx context.Context, arg UpsertSystemErrorParams) error {
	_, err := q.db.Exec(ctx, upsertSystemError,
		arg.ID,
		arg.Source,
		arg.Title,
		arg.Details,
		arg.Severity,
		arg.IsHandled,
		arg.SuggestedFix,
		arg.CreatedAt,
	)
	return err
}
