// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package partnerdb

import (
	"context"
)

type Querier interface {
	CreateQuickTemplate(ctx context.Context, arg CreateQuickTemplateParams) (QuickTemplate, error)
	DeleteQuickTemplate(ctx context.Context, id int64) error
	// ============================================================
	// 7. AI Learning Report
	// ============================================================
	GetAILearningReportStats(ctx context.Context) (GetAILearningReportStatsRow, error)
	// ============================================================
	// 2. AI Performance Report
	// ============================================================
	GetAIPerformanceMetrics(ctx context.Context, arg GetAIPerformanceMetricsParams) (GetAIPerformanceMetricsRow, error)
	GetAITrendDaily(ctx context.Context, arg GetAITrendDailyParams) ([]GetAITrendDailyRow, error)
	// ============================================================
	// 4. Customer Experience (CX) Report
	// ============================================================
	GetCXMetricsReport(ctx context.Context, arg GetCXMetricsReportParams) (GetCXMetricsReportRow, error)
	GetDashboardAutomationTrendDaily(ctx context.Context, arg GetDashboardAutomationTrendDailyParams) ([]GetDashboardAutomationTrendDailyRow, error)
	// ============================================================
	// Partner — dashboard KPIs & trend
	// ============================================================
	GetDashboardKpiSummary(ctx context.Context, arg GetDashboardKpiSummaryParams) (GetDashboardKpiSummaryRow, error)
	// ============================================================
	// 1. General Overview Report
	// ============================================================
	GetGeneralOverviewMetrics(ctx context.Context, arg GetGeneralOverviewMetricsParams) (GetGeneralOverviewMetricsRow, error)
	// ============================================================
	// 5. Operational Load Report
	// ============================================================
	GetHourlyOperationalLoad(ctx context.Context, arg GetHourlyOperationalLoadParams) ([]GetHourlyOperationalLoadRow, error)
	// ============================================================
	// 6. Issue Analysis Report
	// ============================================================
	GetIssueAnalysisReport(ctx context.Context, arg GetIssueAnalysisReportParams) ([]GetIssueAnalysisReportRow, error)
	// ============================================================
	// Partner — system prompt history
	// ============================================================
	GetLatestSystemPrompt(ctx context.Context) (SystemPromptHistory, error)
	// ============================================================
	// 3. Staff Performance Report
	// ============================================================
	GetStaffPerformanceReport(ctx context.Context, arg GetStaffPerformanceReportParams) ([]GetStaffPerformanceReportRow, error)
	// ============================================================
	// Partner — audit logs
	// ============================================================
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (SystemAuditLog, error)
	InsertCSATFeedback(ctx context.Context, arg InsertCSATFeedbackParams) (CsatFeedback, error)
	InsertIssueCategory(ctx context.Context, arg InsertIssueCategoryParams) (IssueCategory, error)
	InsertSystemPromptHistory(ctx context.Context, arg InsertSystemPromptHistoryParams) (SystemPromptHistory, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]SystemAuditLog, error)
	ListInteractedCustomers(ctx context.Context, arg ListInteractedCustomersParams) ([]Guest, error)
	ListOverviewCases(ctx context.Context, arg ListOverviewCasesParams) ([]ListOverviewCasesRow, error)
	// ============================================================
	// Partner — quick templates
	// ============================================================
	ListQuickTemplates(ctx context.Context) ([]QuickTemplate, error)
	// ============================================================
	// Partner — role permissions (RBAC)
	// ============================================================
	ListRolePermissions(ctx context.Context) ([]RolePermission, error)
	ListSystemErrors(ctx context.Context) ([]SystemError, error)
	ListSystemPromptHistory(ctx context.Context, arg ListSystemPromptHistoryParams) ([]SystemPromptHistory, error)
	MarkSystemErrorHandled(ctx context.Context, id string) error
	// ============================================================
	// Partner — system errors (auto-purge after 30 days)
	// ============================================================
	PurgeOldSystemErrors(ctx context.Context) error
	UpdateQuickTemplate(ctx context.Context, arg UpdateQuickTemplateParams) error
	UpsertRolePermission(ctx context.Context, arg UpsertRolePermissionParams) error
	UpsertSystemError(ctx context.Context, arg UpsertSystemErrorParams) error
}

var _ Querier = (*Queries)(nil)
