// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package settingsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AlertConfig struct {
	ID             int64              `json:"id"`
	IsEnabled      bool               `json:"is_enabled"`
	TimeoutSeconds int32              `json:"timeout_seconds"`
	AlertContent   string             `json:"alert_content"`
	UpdatedBy      string             `json:"updated_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AlertEvent struct {
	ID             int64              `json:"id"`
	SessionID      string             `json:"session_id"`
	TimeoutSeconds int32              `json:"timeout_seconds"`
	TriggeredAt    pgtype.Timestamptz `json:"triggered_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	IsResolved     bool               `json:"is_resolved"`
}

type CallEvent struct {
	ID        int64              `json:"id"`
	CallID    string             `json:"call_id"`
	EventType string             `json:"event_type"`
	Source    string             `json:"source"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CallRecording struct {
	ID            int64              `json:"id"`
	CallID        string             `json:"call_id"`
	RecordingUrl  string             `json:"recording_url"`
	FileSizeBytes pgtype.Int8        `json:"file_size_bytes"`
	Transcript    pgtype.Text        `json:"transcript"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type CallSession struct {
	CallID            string             `json:"call_id"`
	CustomerChannelID pgtype.Text        `json:"customer_channel_id"`
	AgentChannelID    pgtype.Text        `json:"agent_channel_id"`
	BridgeID          pgtype.Text        `json:"bridge_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type CallsV2 struct {
	ID              string             `json:"id"`
	SessionID       string             `json:"session_id"`
	CustomerID      string             `json:"customer_id"`
	AgentID         pgtype.Text        `json:"agent_id"`
	Status          interface{}        `json:"status"`
	RequestedAt     pgtype.Timestamptz `json:"requested_at"`
	AssignedAt      pgtype.Timestamptz `json:"assigned_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CaseTag struct {
	ID         int64              `json:"id"`
	SessionID  string             `json:"session_id"`
	TagID      int64              `json:"tag_id"`
	AssignedBy string             `json:"assigned_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CaseTagHistory struct {
	ID          int64              `json:"id"`
	SessionID   string             `json:"session_id"`
	TagID       int64              `json:"tag_id"`
	TagName     string             `json:"tag_name"`
	TagColor    string             `json:"tag_color"`
	Action      string             `json:"action"`
	PerformedBy string             `json:"performed_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ChatCase struct {
	ID             int64              `json:"id"`
	SessionID      string             `json:"session_id"`
	GuestID        pgtype.UUID        `json:"guest_id"`
	CustomerName   string             `json:"customer_name"`
	Status         interface{}        `json:"status"`
	AssignedCs     pgtype.Text        `json:"assigned_cs"`
	LastMessage    pgtype.Text        `json:"last_message"`
	ResolutionNote pgtype.Text        `json:"resolution_note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CustomerPhone  string             `json:"customer_phone"`
}

type ChatMessage struct {
	ID          int64              `json:"id"`
	SessionID   string             `json:"session_id"`
	SenderType  interface{}        `json:"sender_type"`
	SenderID    pgtype.Text        `json:"sender_id"`
	Content     string             `json:"content"`
	ClientMsgID pgtype.UUID        `json:"client_msg_id"`
	IsLearned   bool               `json:"is_learned"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ChatTag struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Color       string             `json:"color"`
	CreatedBy   string             `json:"created_by"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CsatFeedback struct {
	ID            int64              `json:"id"`
	SessionID     string             `json:"session_id"`
	Rating        int32              `json:"rating"`
	FeedbackText  pgtype.Text        `json:"feedback_text"`
	TargetType    string             `json:"target_type"`
	StaffUsername pgtype.Text        `json:"staff_username"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Guest struct {
	ID          int64              `json:"id"`
	GuestID     pgtype.UUID        `json:"guest_id"`
	DisplayName string             `json:"display_name"`
	Phone       pgtype.Text        `json:"phone"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type IssueCategory struct {
	ID           int64              `json:"id"`
	SessionID    string             `json:"session_id"`
	CategoryName string             `json:"category_name"`
	AiResolved   bool               `json:"ai_resolved"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type LearningQueue struct {
	ID         int64              `json:"id"`
	SessionID  pgtype.Text        `json:"session_id"`
	Question   string             `json:"question"`
	Answer     string             `json:"answer"`
	Status     interface{}        `json:"status"`
	CreatedBy  pgtype.Text        `json:"created_by"`
	ApprovedBy pgtype.Text        `json:"approved_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
}

type QuickTemplate struct {
	ID        int64              `json:"id"`
	Title     string             `json:"title"`
	Category  string             `json:"category"`
	Content   string             `json:"content"`
	CreatedBy pgtype.Text        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	ID              int64              `json:"id"`
	RoleName        string             `json:"role_name"`
	FeatureKey      string             `json:"feature_key"`
	PermissionLevel string             `json:"permission_level"`
	CanView         bool               `json:"can_view"`
	CanEdit         bool               `json:"can_edit"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        int64              `json:"id"`
	Token     string             `json:"token"`
	Username  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type SystemAuditLog struct {
	ID          int64              `json:"id"`
	ActionType  string             `json:"action_type"`
	Details     pgtype.Text        `json:"details"`
	PerformedBy pgtype.Text        `json:"performed_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SystemError struct {
	ID           string             `json:"id"`
	Source       string             `json:"source"`
	Title        string             `json:"title"`
	Details      pgtype.Text        `json:"details"`
	Severity     string             `json:"severity"`
	IsHandled    bool               `json:"is_handled"`
	SuggestedFix pgtype.Text        `json:"suggested_fix"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SystemPromptHistory struct {
	ID           int64              `json:"id"`
	SystemPrompt string             `json:"system_prompt"`
	LlmModel     string             `json:"llm_model"`
	Temperature  pgtype.Numeric     `json:"temperature"`
	CreatedBy    pgtype.Text        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SystemSetting struct {
	SettingKey   string `json:"setting_key"`
	SettingValue string `json:"setting_value"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Salt         string             `json:"salt"`
	FullName     string             `json:"full_name"`
	Role         interface{}        `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type VoiceCall struct {
	ID              int64              `json:"id"`
	SessionID       string             `json:"session_id"`
	CallerType      interface{}        `json:"caller_type"`
	CallerID        string             `json:"caller_id"`
	CalleeType      interface{}        `json:"callee_type"`
	CalleeID        string             `json:"callee_id"`
	Status          interface{}        `json:"status"`
	DurationSeconds int32              `json:"duration_seconds"`
	RecordingUrl    pgtype.Text        `json:"recording_url"`
	Transcript      pgtype.Text        `json:"transcript"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
}
