// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package settingsdb

import (
	"context"
)

type Querier interface {
	// ============================================================
	// System settings (KV store)
	// ============================================================
	GetSetting(ctx context.Context, settingKey string) (string, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
