#!/bin/sh
# =============================================================================
# docker-entrypoint.sh — render nginx config templates, then exec nginx.
# =============================================================================
# Usage: this script is the container ENTRYPOINT. The CMD (e.g. "nginx -g
# 'daemon off;'") is passed as $@. We render *.conf.template files in
# /etc/nginx/conf.d/ into *.conf by substituting a small allow-list of
# environment variables, then optionally strip the SSL block if SSL is not
# enabled.
#
# Supported env vars:
#   NGINX_SERVER_NAME    virtual host (default: _)
#   UPLOAD_LIMIT         client_max_body_size (default: 50M)
#   NGINX_ENABLE_SSL     "true" to keep the SSL block (default: unset/disabled)
#   SSL_CERT_PATH        path to fullchain.pem (default: /etc/nginx/ssl/fullchain.pem)
#   SSL_KEY_PATH         path to privkey.pem  (default: /etc/nginx/ssl/privkey.pem)
# =============================================================================
set -eu

CONF_DIR="${CONF_DIR:-/etc/nginx/conf.d}"

# Export defaults so envsubst can fall back to them when the variable
# is referenced with `${VAR:-default}` in the templates.
export NGINX_SERVER_NAME="${NGINX_SERVER_NAME:-_}"
export UPLOAD_LIMIT="${UPLOAD_LIMIT:-50M}"
export NGINX_ENABLE_SSL="${NGINX_ENABLE_SSL:-false}"
export SSL_CERT_PATH="${SSL_CERT_PATH:-/etc/nginx/ssl/fullchain.pem}"
export SSL_KEY_PATH="${SSL_KEY_PATH:-/etc/nginx/ssl/privkey.pem}"

echo "[nginx-entrypoint] server_name=${NGINX_SERVER_NAME} upload_limit=${UPLOAD_LIMIT} ssl=${NGINX_ENABLE_SSL}"

# ---- Render templates --------------------------------------------------------
for f in "${CONF_DIR}"/*.template; do
    if [ -f "$f" ]; then
        out="${f%.template}"
        echo "[nginx-entrypoint] rendering $f -> $out"
        # Only substitute the allow-listed variables to avoid leaking secrets.
        envsubst '${NGINX_SERVER_NAME} ${UPLOAD_LIMIT} ${NGINX_ENABLE_SSL} ${SSL_CERT_PATH} ${SSL_KEY_PATH}' \
            < "$f" > "$out"
    fi
done

# ---- Strip SSL block if disabled --------------------------------------------
# The SSL block in dongdo.conf.template is wrapped in marker comments:
#   # >>> SSL_BLOCK_START
#   ...
#   # <<< SSL_BLOCK_END
# When NGINX_ENABLE_SSL != "true", delete everything between (and including)
# those markers from the rendered file.
if [ "${NGINX_ENABLE_SSL}" != "true" ]; then
    rendered="${CONF_DIR}/dongdo.conf"
    if [ -f "$rendered" ]; then
        # shellcheck disable=SC3037  # -i works on busybox sed in alpine
        sed -i '/# >>> SSL_BLOCK_START/,/# <<< SSL_BLOCK_END/d' "$rendered"
        echo "[nginx-entrypoint] SSL block stripped (NGINX_ENABLE_SSL!=true)"
    fi
    rm -f "${CONF_DIR}/00-ssl-redirect.conf"
else
    # Emit a dedicated redirect server that takes over :80 and 301-redirects
    # every request to https://. This file is included via the wildcard
    # `include /etc/nginx/conf.d/*.conf` in nginx.conf, and it deliberately
    # uses `listen 80 default_server` so it wins the catch-all.
    cat > "${CONF_DIR}/00-ssl-redirect.conf" <<'EOF'
# Auto-generated by docker-entrypoint.sh when NGINX_ENABLE_SSL=true.
# Handles ACME challenges AND redirects all other HTTP traffic to HTTPS.
# This file is named "00-*" so it loads BEFORE dongdo.conf, but both
# blocks share the same server_name. nginx picks the FIRST match for a
# given server_name, so this block wins for ${NGINX_SERVER_NAME}.
# ACME challenges are served from /var/www/certbot (bind-mounted by certbot).
server {
    listen 80;
    listen [::]:80;
    # Use the same server_name as dongdo.conf so nginx selects this block
    # for all requests to that host. Requests without a matching Host
    # header fall through to the dongdo.conf default_server slot instead.
    server_name _;
    server_tokens off;
    access_log off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
EOF
    echo "[nginx-entrypoint] SSL redirect enabled (NGINX_SERVER_NAME=${NGINX_SERVER_NAME})"
fi

# ---- Validate and run --------------------------------------------------------
echo "[nginx-entrypoint] validating nginx config..."
nginx -t

echo "[nginx-entrypoint] handing off to: $@"
exec "$@"
