// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package analyticsdb

import (
	"context"
)

const getAnalyticsStats = `-- name: GetAnalyticsStats :one

SELECT
    (SELECT COUNT(*) FROM chat_cases)::int                                            AS total_cases,
    (SELECT COUNT(DISTINCT session_id) FROM chat_messages)::int                       AS total_sessions,
    (SELECT COUNT(*) FROM chat_cases WHERE status = 'AI_ACTIVE')::int                  AS ai_active_cases,
    (SELECT COUNT(*) FROM chat_cases WHERE status = 'NEEDS_HUMAN_CS')::int             AS needs_human_cases,
    (SELECT COUNT(*) FROM chat_cases WHERE status = 'HUMAN_CS_ACTIVE')::int            AS active_human_cases,
    (SELECT COUNT(*) FROM chat_cases WHERE status = 'RESOLVED')::int                   AS resolved_cases,
    (SELECT COUNT(*) FROM learning_queue WHERE status = 'APPROVED')::int               AS total_learned_qa,
    (SELECT COUNT(*) FROM learning_queue WHERE status = 'PENDING')::int                AS pending_learn_count
`

type GetAnalyticsStatsRow struct {
	TotalCases        int32 `json:"total_cases"`
	TotalSessions     int32 `json:"total_sessions"`
	AiActiveCases     int32 `json:"ai_active_cases"`
	NeedsHumanCases   int32 `json:"needs_human_cases"`
	ActiveHumanCases  int32 `json:"active_human_cases"`
	ResolvedCases     int32 `json:"resolved_cases"`
	TotalLearnedQa    int32 `json:"total_learned_qa"`
	PendingLearnCount int32 `json:"pending_learn_count"`
}

// ============================================================
// Analytics dashboard stats
// ============================================================
func (q *Queries) GetAnalyticsStats(ctx context.Context) (GetAnalyticsStatsRow, error) {
	row := q.db.QueryRow(ctx, getAnalyticsStats)
	var i GetAnalyticsStatsRow
	err := row.Scan(
		&i.TotalCases,
		&i.TotalSessions,
		&i.AiActiveCases,
		&i.NeedsHumanCases,
		&i.ActiveHumanCases,
		&i.ResolvedCases,
		&i.TotalLearnedQa,
		&i.PendingLearnCount,
	)
	return i, err
}
