// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package analyticsdb

import (
	"context"
)

type Querier interface {
	// ============================================================
	// Analytics dashboard stats
	// ============================================================
	GetAnalyticsStats(ctx context.Context) (GetAnalyticsStatsRow, error)
}

var _ Querier = (*Queries)(nil)
