;/etc/asterisk/cli_aliases.conf - Convenience CLI aliases
;=================================================================================
; `asterisk -rx` shortcuts used by `/scripts/test_call.sh` and Makefile.
;=================================================================================

[default]
; quick queue status
; hi -> show queue stats

; Format:
; alias = -> =<substituted command>

; hi = core show hints
; hq = queue show

peers = pjsip show endpoints
regs = pjsip show registrations
calls = core show calls
up = core show uptime
ver = core show version