// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authdb

import (
	"context"
)

type Querier interface {
	CountUsersByUsername(ctx context.Context, username string) (int32, error)
	// ============================================================
	// Auth sessions
	// ============================================================
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// ============================================================
	// Users (CSKH Staff & Admin)
	// ============================================================
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, token string) error
	DeleteUser(ctx context.Context, username string) error
	DeleteUserByUsernameInsensitive(ctx context.Context, lower string) error
	DeleteUserSessions(ctx context.Context, username string) error
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserByUsernameInsensitive(ctx context.Context, lower string) (User, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	ListUsersByRoleAndSearch(ctx context.Context, arg ListUsersByRoleAndSearchParams) ([]ListUsersByRoleAndSearchRow, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdatePasswordByUsernameInsensitive(ctx context.Context, arg UpdatePasswordByUsernameInsensitiveParams) error
	UpdateUserWithPassword(ctx context.Context, arg UpdateUserWithPasswordParams) (UpdateUserWithPasswordRow, error)
	UpdateUserWithoutPassword(ctx context.Context, arg UpdateUserWithoutPasswordParams) (UpdateUserWithoutPasswordRow, error)
	VerifySession(ctx context.Context, token string) (VerifySessionRow, error)
}

var _ Querier = (*Queries)(nil)
