// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package authdb

import (
	"context"
	"time"

	"github.com/hoainguyen222/DongDo_CS_V2/internal/domain"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (token, username, created_at, expires_at)
VALUES ($1, $2, NOW(), $3)
RETURNING id, token, username, created_at, expires_at
`

type CreateSessionParams struct {
	Token     string    `json:"token"`
	Username  string    `json:"username"`
	ExpiresAt time.Time `json:"expires_at"`
}

// ============================================================
// Auth sessions
// ============================================================
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.Token, arg.Username, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Username,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE username = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, username)
	return err
}

const verifySession = `-- name: VerifySession :one
SELECT s.username, u.full_name, u.role
FROM sessions s
JOIN users u ON s.username = u.username
WHERE s.token = $1 AND s.expires_at > NOW() AND u.is_active = TRUE
`

type VerifySessionRow struct {
	Username string          `json:"username"`
	FullName string          `json:"full_name"`
	Role     domain.UserRole `json:"role"`
}

func (q *Queries) VerifySession(ctx context.Context, token string) (VerifySessionRow, error) {
	row := q.db.QueryRow(ctx, verifySession, token)
	var i VerifySessionRow
	err := row.Scan(&i.Username, &i.FullName, &i.Role)
	return i, err
}
