// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package authdb

import (
	"context"
	"time"

	"github.com/hoainguyen222/DongDo_CS_V2/internal/domain"
)

const countUsersByUsername = `-- name: CountUsersByUsername :one
SELECT COUNT(*)::int FROM users WHERE username = $1
`

func (q *Queries) CountUsersByUsername(ctx context.Context, username string) (int32, error) {
	row := q.db.QueryRow(ctx, countUsersByUsername, username)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (username, password_hash, salt, full_name, role, is_active, created_at)
VALUES ($1, $2, $3, $4, $5, TRUE, NOW())
RETURNING id, username, full_name, role, is_active, created_at
`

type CreateUserParams struct {
	Username     string          `json:"username"`
	PasswordHash string          `json:"password_hash"`
	Salt         string          `json:"salt"`
	FullName     string          `json:"full_name"`
	Role         domain.UserRole `json:"role"`
}

type CreateUserRow struct {
	ID        int64           `json:"id"`
	Username  string          `json:"username"`
	FullName  string          `json:"full_name"`
	Role      domain.UserRole `json:"role"`
	IsActive  bool            `json:"is_active"`
	CreatedAt time.Time       `json:"created_at"`
}

// ============================================================
// Users (CSKH Staff & Admin)
// ============================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Salt,
		arg.FullName,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE username = $1
`

func (q *Queries) DeleteUser(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, deleteUser, username)
	return err
}

const deleteUserByUsernameInsensitive = `-- name: DeleteUserByUsernameInsensitive :exec
DELETE FROM users WHERE LOWER(username) = LOWER($1)
`

func (q *Queries) DeleteUserByUsernameInsensitive(ctx context.Context, lower string) error {
	_, err := q.db.Exec(ctx, deleteUserByUsernameInsensitive, lower)
	return err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, salt, full_name, role, is_active, created_at
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Salt,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsernameInsensitive = `-- name: GetUserByUsernameInsensitive :one
SELECT id, username, password_hash, salt, full_name, role, is_active, created_at
FROM users
WHERE LOWER(username) = LOWER($1)
`

func (q *Queries) GetUserByUsernameInsensitive(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameInsensitive, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Salt,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, full_name, role, is_active, created_at
FROM users
ORDER BY id ASC
`

type ListUsersRow struct {
	ID        int64           `json:"id"`
	Username  string          `json:"username"`
	FullName  string          `json:"full_name"`
	Role      domain.UserRole `json:"role"`
	IsActive  bool            `json:"is_active"`
	CreatedAt time.Time       `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRoleAndSearch = `-- name: ListUsersByRoleAndSearch :many
SELECT id, username, full_name, role, is_active, created_at
FROM users
WHERE ($1::text = 'ALL' OR role::text = $1)
  AND ($2::text = '' OR username ILIKE '%' || $2 || '%' OR full_name ILIKE '%' || $2 || '%')
ORDER BY id ASC
`

type ListUsersByRoleAndSearchParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

type ListUsersByRoleAndSearchRow struct {
	ID        int64           `json:"id"`
	Username  string          `json:"username"`
	FullName  string          `json:"full_name"`
	Role      domain.UserRole `json:"role"`
	IsActive  bool            `json:"is_active"`
	CreatedAt time.Time       `json:"created_at"`
}

func (q *Queries) ListUsersByRoleAndSearch(ctx context.Context, arg ListUsersByRoleAndSearchParams) ([]ListUsersByRoleAndSearchRow, error) {
	rows, err := q.db.Query(ctx, listUsersByRoleAndSearch, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByRoleAndSearchRow{}
	for rows.Next() {
		var i ListUsersByRoleAndSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash = $1, salt = $2 WHERE username = $3
`

type UpdatePasswordParams struct {
	PasswordHash string `json:"password_hash"`
	Salt         string `json:"salt"`
	Username     string `json:"username"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.PasswordHash, arg.Salt, arg.Username)
	return err
}

const updatePasswordByUsernameInsensitive = `-- name: UpdatePasswordByUsernameInsensitive :exec
UPDATE users SET password_hash = $1, salt = $2 WHERE LOWER(username) = LOWER($3)
`

type UpdatePasswordByUsernameInsensitiveParams struct {
	PasswordHash string `json:"password_hash"`
	Salt         string `json:"salt"`
	Lower        string `json:"lower"`
}

func (q *Queries) UpdatePasswordByUsernameInsensitive(ctx context.Context, arg UpdatePasswordByUsernameInsensitiveParams) error {
	_, err := q.db.Exec(ctx, updatePasswordByUsernameInsensitive, arg.PasswordHash, arg.Salt, arg.Lower)
	return err
}

const updateUserWithPassword = `-- name: UpdateUserWithPassword :one
UPDATE users
SET full_name = $1, role = $2, is_active = $3, password_hash = $4, salt = $5
WHERE LOWER(username) = LOWER($6)
RETURNING id, username, full_name, role, is_active, created_at
`

type UpdateUserWithPasswordParams struct {
	FullName     string          `json:"full_name"`
	Role         domain.UserRole `json:"role"`
	IsActive     bool            `json:"is_active"`
	PasswordHash string          `json:"password_hash"`
	Salt         string          `json:"salt"`
	Lower        string          `json:"lower"`
}

type UpdateUserWithPasswordRow struct {
	ID        int64           `json:"id"`
	Username  string          `json:"username"`
	FullName  string          `json:"full_name"`
	Role      domain.UserRole `json:"role"`
	IsActive  bool            `json:"is_active"`
	CreatedAt time.Time       `json:"created_at"`
}

func (q *Queries) UpdateUserWithPassword(ctx context.Context, arg UpdateUserWithPasswordParams) (UpdateUserWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, updateUserWithPassword,
		arg.FullName,
		arg.Role,
		arg.IsActive,
		arg.PasswordHash,
		arg.Salt,
		arg.Lower,
	)
	var i UpdateUserWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserWithoutPassword = `-- name: UpdateUserWithoutPassword :one
UPDATE users
SET full_name = $1, role = $2, is_active = $3
WHERE LOWER(username) = LOWER($4)
RETURNING id, username, full_name, role, is_active, created_at
`

type UpdateUserWithoutPasswordParams struct {
	FullName string          `json:"full_name"`
	Role     domain.UserRole `json:"role"`
	IsActive bool            `json:"is_active"`
	Lower    string          `json:"lower"`
}

type UpdateUserWithoutPasswordRow struct {
	ID        int64           `json:"id"`
	Username  string          `json:"username"`
	FullName  string          `json:"full_name"`
	Role      domain.UserRole `json:"role"`
	IsActive  bool            `json:"is_active"`
	CreatedAt time.Time       `json:"created_at"`
}

func (q *Queries) UpdateUserWithoutPassword(ctx context.Context, arg UpdateUserWithoutPasswordParams) (UpdateUserWithoutPasswordRow, error) {
	row := q.db.QueryRow(ctx, updateUserWithoutPassword,
		arg.FullName,
		arg.Role,
		arg.IsActive,
		arg.Lower,
	)
	var i UpdateUserWithoutPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
