// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning.sql

package learningdb

import (
	"context"

	"github.com/hoainguyen222/DongDo_CS_V2/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

const addToLearningQueue = `-- name: AddToLearningQueue :one

INSERT INTO learning_queue (session_id, question, answer, status, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, session_id, question, answer, status, created_by, approved_by, created_at, approved_at
`

type AddToLearningQueueParams struct {
	SessionID pgtype.Text        `json:"session_id"`
	Question  string             `json:"question"`
	Answer    string             `json:"answer"`
	Status    domain.LearnStatus `json:"status"`
	CreatedBy pgtype.Text        `json:"created_by"`
}

// ============================================================
// Learning queue (knowledge extraction)
// ============================================================
func (q *Queries) AddToLearningQueue(ctx context.Context, arg AddToLearningQueueParams) (LearningQueue, error) {
	row := q.db.QueryRow(ctx, addToLearningQueue,
		arg.SessionID,
		arg.Question,
		arg.Answer,
		arg.Status,
		arg.CreatedBy,
	)
	var i LearningQueue
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Question,
		&i.Answer,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const clearAllLearning = `-- name: ClearAllLearning :exec
DELETE FROM learning_queue
`

func (q *Queries) ClearAllLearning(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearAllLearning)
	return err
}

const deleteSessionLearning = `-- name: DeleteSessionLearning :exec
DELETE FROM learning_queue WHERE session_id = $1 AND status = 'PENDING'::learn_status
`

func (q *Queries) DeleteSessionLearning(ctx context.Context, sessionID pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteSessionLearning, sessionID)
	return err
}

const getLearningItem = `-- name: GetLearningItem :one
SELECT id, session_id, question, answer, status, created_by, approved_by, created_at, approved_at
FROM learning_queue
WHERE id = $1
`

func (q *Queries) GetLearningItem(ctx context.Context, id int64) (LearningQueue, error) {
	row := q.db.QueryRow(ctx, getLearningItem, id)
	var i LearningQueue
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Question,
		&i.Answer,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const listAllLearning = `-- name: ListAllLearning :many
SELECT id, session_id, question, answer, status, created_by, approved_by, created_at, approved_at
FROM learning_queue
ORDER BY id DESC
`

func (q *Queries) ListAllLearning(ctx context.Context) ([]LearningQueue, error) {
	rows, err := q.db.Query(ctx, listAllLearning)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningQueue{}
	for rows.Next() {
		var i LearningQueue
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Question,
			&i.Answer,
			&i.Status,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.CreatedAt,
			&i.ApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningByStatus = `-- name: ListLearningByStatus :many
SELECT id, session_id, question, answer, status, created_by, approved_by, created_at, approved_at
FROM learning_queue
WHERE status = $1::learn_status
ORDER BY id DESC
`

func (q *Queries) ListLearningByStatus(ctx context.Context, dollar_1 domain.LearnStatus) ([]LearningQueue, error) {
	rows, err := q.db.Query(ctx, listLearningByStatus, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningQueue{}
	for rows.Next() {
		var i LearningQueue
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Question,
			&i.Answer,
			&i.Status,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.CreatedAt,
			&i.ApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLearningStatus = `-- name: MarkLearningStatus :exec
UPDATE learning_queue
SET status = $1::learn_status, approved_by = $2, approved_at = NOW()
WHERE id = $3
`

type MarkLearningStatusParams struct {
	Column1    domain.LearnStatus `json:"column_1"`
	ApprovedBy pgtype.Text        `json:"approved_by"`
	ID         int64              `json:"id"`
}

func (q *Queries) MarkLearningStatus(ctx context.Context, arg MarkLearningStatusParams) error {
	_, err := q.db.Exec(ctx, markLearningStatus, arg.Column1, arg.ApprovedBy, arg.ID)
	return err
}

const updateLearningContent = `-- name: UpdateLearningContent :exec
UPDATE learning_queue SET question = $1, answer = $2 WHERE id = $3
`

type UpdateLearningContentParams struct {
	Question string `json:"question"`
	Answer   string `json:"answer"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateLearningContent(ctx context.Context, arg UpdateLearningContentParams) error {
	_, err := q.db.Exec(ctx, updateLearningContent, arg.Question, arg.Answer, arg.ID)
	return err
}
