// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package learningdb

import (
	"context"

	"github.com/hoainguyen222/DongDo_CS_V2/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ============================================================
	// Learning queue (knowledge extraction)
	// ============================================================
	AddToLearningQueue(ctx context.Context, arg AddToLearningQueueParams) (LearningQueue, error)
	ClearAllLearning(ctx context.Context) error
	DeleteSessionLearning(ctx context.Context, sessionID pgtype.Text) error
	GetLearningItem(ctx context.Context, id int64) (LearningQueue, error)
	ListAllLearning(ctx context.Context) ([]LearningQueue, error)
	ListLearningByStatus(ctx context.Context, dollar_1 domain.LearnStatus) ([]LearningQueue, error)
	MarkLearningStatus(ctx context.Context, arg MarkLearningStatusParams) error
	UpdateLearningContent(ctx context.Context, arg UpdateLearningContentParams) error
}

var _ Querier = (*Queries)(nil)
