// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package voicedb

import (
	"time"

	"github.com/google/uuid"
	"github.com/hoainguyen222/DongDo_CS_V2/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatCase struct {
	ID             int64       `json:"id"`
	SessionID      string      `json:"session_id"`
	GuestID        pgtype.UUID `json:"guest_id"`
	CustomerName   string      `json:"customer_name"`
	Status         interface{} `json:"status"`
	AssignedCs     pgtype.Text `json:"assigned_cs"`
	LastMessage    pgtype.Text `json:"last_message"`
	ResolutionNote pgtype.Text `json:"resolution_note"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	CustomerPhone  string      `json:"customer_phone"`
}

type ChatMessage struct {
	ID          int64       `json:"id"`
	SessionID   string      `json:"session_id"`
	SenderType  interface{} `json:"sender_type"`
	SenderID    pgtype.Text `json:"sender_id"`
	Content     string      `json:"content"`
	ClientMsgID pgtype.UUID `json:"client_msg_id"`
	IsLearned   bool        `json:"is_learned"`
	CreatedAt   time.Time   `json:"created_at"`
}

type CsatFeedback struct {
	ID            int64       `json:"id"`
	SessionID     string      `json:"session_id"`
	Rating        int32       `json:"rating"`
	FeedbackText  pgtype.Text `json:"feedback_text"`
	TargetType    string      `json:"target_type"`
	StaffUsername pgtype.Text `json:"staff_username"`
	CreatedAt     time.Time   `json:"created_at"`
}

type Guest struct {
	ID          int64       `json:"id"`
	GuestID     uuid.UUID   `json:"guest_id"`
	DisplayName string      `json:"display_name"`
	Phone       pgtype.Text `json:"phone"`
	CreatedAt   time.Time   `json:"created_at"`
}

type IssueCategory struct {
	ID           int64     `json:"id"`
	SessionID    string    `json:"session_id"`
	CategoryName string    `json:"category_name"`
	AiResolved   bool      `json:"ai_resolved"`
	CreatedAt    time.Time `json:"created_at"`
}

type LearningQueue struct {
	ID         int64              `json:"id"`
	SessionID  pgtype.Text        `json:"session_id"`
	Question   string             `json:"question"`
	Answer     string             `json:"answer"`
	Status     interface{}        `json:"status"`
	CreatedBy  pgtype.Text        `json:"created_by"`
	ApprovedBy pgtype.Text        `json:"approved_by"`
	CreatedAt  time.Time          `json:"created_at"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
}

type QuickTemplate struct {
	ID        int64       `json:"id"`
	Title     string      `json:"title"`
	Category  string      `json:"category"`
	Content   string      `json:"content"`
	CreatedBy pgtype.Text `json:"created_by"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type RolePermission struct {
	ID              int64     `json:"id"`
	RoleName        string    `json:"role_name"`
	FeatureKey      string    `json:"feature_key"`
	PermissionLevel string    `json:"permission_level"`
	CanView         bool      `json:"can_view"`
	CanEdit         bool      `json:"can_edit"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Session struct {
	ID        int64     `json:"id"`
	Token     string    `json:"token"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type SystemAuditLog struct {
	ID          int64       `json:"id"`
	ActionType  string      `json:"action_type"`
	Details     pgtype.Text `json:"details"`
	PerformedBy pgtype.Text `json:"performed_by"`
	CreatedAt   time.Time   `json:"created_at"`
}

type SystemError struct {
	ID           string      `json:"id"`
	Source       string      `json:"source"`
	Title        string      `json:"title"`
	Details      pgtype.Text `json:"details"`
	Severity     string      `json:"severity"`
	IsHandled    bool        `json:"is_handled"`
	SuggestedFix pgtype.Text `json:"suggested_fix"`
	CreatedAt    time.Time   `json:"created_at"`
}

type SystemPromptHistory struct {
	ID           int64          `json:"id"`
	SystemPrompt string         `json:"system_prompt"`
	LlmModel     string         `json:"llm_model"`
	Temperature  pgtype.Numeric `json:"temperature"`
	CreatedBy    pgtype.Text    `json:"created_by"`
	CreatedAt    time.Time      `json:"created_at"`
}

type SystemSetting struct {
	SettingKey   string `json:"setting_key"`
	SettingValue string `json:"setting_value"`
}

type User struct {
	ID           int64       `json:"id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Salt         string      `json:"salt"`
	FullName     string      `json:"full_name"`
	Role         interface{} `json:"role"`
	IsActive     bool        `json:"is_active"`
	CreatedAt    time.Time   `json:"created_at"`
}

type VoiceCall struct {
	ID              int64              `json:"id"`
	SessionID       string             `json:"session_id"`
	CallerType      domain.CallerType  `json:"caller_type"`
	CallerID        string             `json:"caller_id"`
	CalleeType      domain.CallerType  `json:"callee_type"`
	CalleeID        string             `json:"callee_id"`
	Status          domain.CallStatus  `json:"status"`
	DurationSeconds int32              `json:"duration_seconds"`
	RecordingUrl    pgtype.Text        `json:"recording_url"`
	Transcript      pgtype.Text        `json:"transcript"`
	CreatedAt       time.Time          `json:"created_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
}
