// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package voicedb

import (
	"context"
)

type Querier interface {
	CountCalls(ctx context.Context, dollar_1 string) (int64, error)
	// ============================================================
	// Voice calls (WebRTC)
	// ============================================================
	CreateVoiceCall(ctx context.Context, arg CreateVoiceCallParams) (VoiceCall, error)
	DeleteCall(ctx context.Context, id int64) error
	EndCall(ctx context.Context, arg EndCallParams) error
	GetCallByID(ctx context.Context, id int64) (VoiceCall, error)
	GetCallsBySession(ctx context.Context, sessionID string) ([]VoiceCall, error)
	ListAllCalls(ctx context.Context, arg ListAllCallsParams) ([]VoiceCall, error)
	ListAllCallsLegacy(ctx context.Context) ([]VoiceCall, error)
	SetCallTranscript(ctx context.Context, arg SetCallTranscriptParams) error
	UpdateCallStatus(ctx context.Context, arg UpdateCallStatusParams) error
}

var _ Querier = (*Queries)(nil)
