// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voice_calls.sql

package voicedb

import (
	"context"

	"github.com/hoainguyen222/DongDo_CS_V2/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVoiceCall = `-- name: CreateVoiceCall :one

INSERT INTO voice_calls (session_id, caller_type, caller_id, callee_type, callee_id, status, created_at)
VALUES ($1, $2, $3, $4, $5, 'RINGING'::call_status, NOW())
RETURNING id, session_id, caller_type, caller_id, callee_type, callee_id,
          status, duration_seconds, recording_url, transcript, created_at, ended_at
`

type CreateVoiceCallParams struct {
	SessionID  string            `json:"session_id"`
	CallerType domain.CallerType `json:"caller_type"`
	CallerID   string            `json:"caller_id"`
	CalleeType domain.CallerType `json:"callee_type"`
	CalleeID   string            `json:"callee_id"`
}

// ============================================================
// Voice calls (WebRTC)
// ============================================================
func (q *Queries) CreateVoiceCall(ctx context.Context, arg CreateVoiceCallParams) (VoiceCall, error) {
	row := q.db.QueryRow(ctx, createVoiceCall,
		arg.SessionID,
		arg.CallerType,
		arg.CallerID,
		arg.CalleeType,
		arg.CalleeID,
	)
	var i VoiceCall
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CallerType,
		&i.CallerID,
		&i.CalleeType,
		&i.CalleeID,
		&i.Status,
		&i.DurationSeconds,
		&i.RecordingUrl,
		&i.Transcript,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const deleteCall = `-- name: DeleteCall :exec
DELETE FROM voice_calls WHERE id = $1
`

const markMissedCall = `-- name: MarkMissedCall :exec
UPDATE voice_calls
SET status = 'MISSED'::call_status,
    duration_seconds = 0,
    ended_at         = NOW()
WHERE id = $1
`

func (q *Queries) MarkMissedCall(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markMissedCall, id)
	return err
}

func (q *Queries) DeleteCall(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCall, id)
	return err
}

const endCall = `-- name: EndCall :exec
UPDATE voice_calls
SET status = 'ENDED'::call_status,
    duration_seconds = $1,
    recording_url    = $2,
    ended_at         = NOW()
WHERE id = $3
`

type EndCallParams struct {
	DurationSeconds int32       `json:"duration_seconds"`
	RecordingUrl    pgtype.Text `json:"recording_url"`
	ID              int64       `json:"id"`
}

func (q *Queries) EndCall(ctx context.Context, arg EndCallParams) error {
	_, err := q.db.Exec(ctx, endCall, arg.DurationSeconds, arg.RecordingUrl, arg.ID)
	return err
}

const getCallByID = `-- name: GetCallByID :one
SELECT id, session_id, caller_type, caller_id, callee_type, callee_id,
       status, duration_seconds, recording_url, transcript, created_at, ended_at
FROM voice_calls
WHERE id = $1
`

func (q *Queries) GetCallByID(ctx context.Context, id int64) (VoiceCall, error) {
	row := q.db.QueryRow(ctx, getCallByID, id)
	var i VoiceCall
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CallerType,
		&i.CallerID,
		&i.CalleeType,
		&i.CalleeID,
		&i.Status,
		&i.DurationSeconds,
		&i.RecordingUrl,
		&i.Transcript,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const getCallsBySession = `-- name: GetCallsBySession :many
SELECT id, session_id, caller_type, caller_id, callee_type, callee_id,
       status, duration_seconds, recording_url, transcript, created_at, ended_at
FROM voice_calls
WHERE session_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCallsBySession(ctx context.Context, sessionID string) ([]VoiceCall, error) {
	rows, err := q.db.Query(ctx, getCallsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceCall{}
	for rows.Next() {
		var i VoiceCall
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CallerType,
			&i.CallerID,
			&i.CalleeType,
			&i.CalleeID,
			&i.Status,
			&i.DurationSeconds,
			&i.RecordingUrl,
			&i.Transcript,
			&i.CreatedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCalls = `-- name: ListAllCalls :many
SELECT id, session_id, caller_type, caller_id, callee_type, callee_id,
       status, duration_seconds, recording_url, transcript, created_at, ended_at
FROM voice_calls
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListAllCalls(ctx context.Context) ([]VoiceCall, error) {
	rows, err := q.db.Query(ctx, listAllCalls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceCall{}
	for rows.Next() {
		var i VoiceCall
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CallerType,
			&i.CallerID,
			&i.CalleeType,
			&i.CalleeID,
			&i.Status,
			&i.DurationSeconds,
			&i.RecordingUrl,
			&i.Transcript,
			&i.CreatedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCallTranscript = `-- name: SetCallTranscript :exec
UPDATE voice_calls SET transcript = $1 WHERE id = $2
`

type SetCallTranscriptParams struct {
	Transcript pgtype.Text `json:"transcript"`
	ID         int64       `json:"id"`
}

func (q *Queries) SetCallTranscript(ctx context.Context, arg SetCallTranscriptParams) error {
	_, err := q.db.Exec(ctx, setCallTranscript, arg.Transcript, arg.ID)
	return err
}

const updateCallStatus = `-- name: UpdateCallStatus :exec
UPDATE voice_calls SET status = $1::call_status, ended_at = NOW() WHERE id = $2
`

type UpdateCallStatusParams struct {
	Column1 domain.CallStatus `json:"column_1"`
	ID      int64             `json:"id"`
}

func (q *Queries) UpdateCallStatus(ctx context.Context, arg UpdateCallStatusParams) error {
	_, err := q.db.Exec(ctx, updateCallStatus, arg.Column1, arg.ID)
	return err
}
